### ISSUE TITLE
JMS connection with IBM-MQ is not getting closed when a stop() signal is received due to an internal exception

### ISSUE THREAD

**Issue by khetanshu** [ibm-messaging/kafka-connect-mq-source#73] opened 2020-11-12 00:58 UTC
Hello, I have encountered an issue wherein the connection with IBM-MQ remains `Inactive` (not closed) when an internal exception occurs in Kafka Connect. **Due to this issue, the batch of messages read in the previous `poll()` remains uncommitted in the IBM-MQ**. 

### Steps to reproduce:

1. Configure `producer.max.request.size=1048576` (1 MB)  in `worker.properties`
2. Now send messages in IBM-MQ with size >= 1MB 
3. Check the logs (you will find an exception stating that the configured `max.request.size` is < than the message received. Also, a statement "`Task is being killed and will not recover until manually restarted`") 
4.  Check the IBM-MQ (you will find the connection is still present; however, its state is `Inactive`)

### Analysis:
Based on the further analysis, I found that when the `stop()`, in `MQSourceTask`, is executed in this scenario, the `JMSReader` **never gets closed**. 

As per the existing `stop()` implementations, if `receivingMessages == TRUE` then `reader.close()`. Which, in this case, will never happen. As `receivingMessages` would be `FALSE`. 

However after negating the condition, the issue seems to be resolved, i.e., if `receivingMessages == FALSE` then `reader.close()`

Existing logic: 
```
synchronized(this) {
   if (receivingMessages.get()) {
        log.debug("Will close connection");
        willClose = true;
   }
 }
if (willClose) {
   // Close the connection to MQ to clean up
   if (reader != null) {
       reader.close();
   }
}
```

New Logic:
```
synchronized(this) {
   if (!receivingMessages.get()) {    // ** added NOT here **
        log.debug("Will close connection");
        willClose = true;
   }
 }
if (willClose) {
   // Close the connection to MQ to clean up
   if (reader != null) {
       reader.close();
   }
}
```

Please share your opinion on this and let me know if it makes sense to make the changes. Thank you !

**Comment by AndrewJSchofield** [comment] 2020-11-12 22:28
Hi. Thanks for raising the issue. I think this is a bug, but your proposed fix is not better. It does ensure that the connection is closed in your specific situation, but it's going to be less reliable over all. The problem is that the thread on which `stop()` is called is not synchronised with the polling thread, and there is the possibility of an exception elsewhere. What is needed is a thread-safe way of calling `reader.close()` once messages are not being received any longer. I think that `reader.close()` after line 148 would be better.

**Comment by khetanshu** [comment] 2020-11-16 21:45
Hi @AndrewJSchofield  Thank you for sharing your views! 

I think even if we call `reader.close()` after [line 148](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/e8ea567053fd75c6484dd6f7db301288d23ae7a0/src/main/java/com/ibm/eventstreams/connect/mqsource/MQSourceTask.java#L148) (i.e., in `poll()`), the issue won't fix because, in this scenario, when an internal exception happens in Kafka Connect, it calls the connector's `stop()` and terminates the task [i.e., no `poll()` later]. For reference, I have attached a snippet of the log. <img width="1684" alt="image" src="https://user-images.githubusercontent.com/33383039/99310981-ad7a6700-2810-11eb-8149-8249ddc05844.png">

I understand your point that `poll()` and `stop()` threads are not synchronized; however, in `stop()` why we want to call `reader.close()` only when we are receiving messages in `poll()`?

Based on the `stop()` comments, 
> Signal this SourceTask to stop. In SourceTasks, this method only needs to signal to the task that it should stop trying to poll for new data and interrupt any outstanding poll() requests

 So shouldn't we call `reader.close()` in `stop()` irrespective of whether we are receiving messages in `poll()`?

**Comment by AndrewJSchofield** [comment] 2020-11-17 08:26
Yes. A synchronised way of doing it will work.

This complexity is because the state machine for source connectors is rather weak at the moment. I did open a Kafka Improvement Proposal (https://cwiki.apache.org/confluence/display/KAFKA/KIP-419%3A+Safely+notify+Kafka+Connect+SourceTask+is+stopped) to address it but it didn't get traction in the community. So, it will be necessary to improve the code in the connector.

**Comment by khetanshu** [comment] 2020-11-17 23:33
Yes, adding a `stopped()` callback to the `SourceTask` interface would certainly make the solution generic across other connectors as well. 

So as we have to improve the connector, here is what I think. 
We can remove the `receivingMessages` completely and make the `reader` usage **synchronized** in `poll()` and `stop(`) using `this` object or a new common locking object say like `readerLock`. 

For example,
Updated `poll()`:
```
.
.
synchronized(this){   // ** This is new **
            if (!stopNow.get()) {
                log.info("Polling for records");
                SourceRecord src;
                do {
                    // For the first message in the batch, wait a while if no message
                    src = reader.receive(messageCount == 0);
                    if (src != null) {
                        msgs.add(src);
                        messageCount++;
                    }
                } while ((src != null) && (messageCount < batchSize) && !stopNow.get());
            }
            else {
                log.info("Stopping polling for records");
            }
}
.
.
```

Updated `stop()`:

```
@Override public void stop() {
        log.trace("[{}] Entry {}.stop", Thread.currentThread().getId(), this.getClass().getName());

        stopNow.set(true);

        synchronized(this) {         // ** This is new **
            // Close the connection to MQ to clean up
            if (reader != null) {
                reader.close();
            }
        }

        log.trace("[{}]  Exit {}.stop", Thread.currentThread().getId(), this.getClass().getName());
}
```

Please let me know if this looks fine to you; I can create a pull request then.

**Comment by AndrewJSchofield** [comment] 2020-11-19 15:06
The `reader.receive()` will block indefinitely for the first message in a batch. This means, the `stop()` method could also block indefinitely.

**Comment by khetanshu** [comment] 2020-11-19 19:55
Oh, I missed that part; Yes, when there is no message in IBM-MQ, the `reader.receive()` will be blocked indefinitely until a message is available. 

I am thinking out loud, so from the current implementation, if we remove the `receivingMessages` as shown below, then when a `stop` signal is received, the task won't try to poll for new data, and it would interrupt any outstanding `poll()` requests. And currently also `reader` usage in `stop()` and `poll()` is not synchronized. 

What could be the issue if we don't synchronize `reader` usage in `poll()` and `stop()`? 

`Poll()` - removed `receivingMessages`:
```
.
.
try {
           // receivingMessages.set(true);   // ** This is new **

            if (!stopNow.get()) {
                log.info("Polling for records");
                SourceRecord src;
                do {
                    // For the first message in the batch, wait a while if no message
                    src = reader.receive(messageCount == 0);
                    if (src != null) {
                        msgs.add(src);
                        messageCount++;
                    }
                } while ((src != null) && (messageCount < batchSize) && !stopNow.get());
            }
            else {
                log.info("Stopping polling for records");
            }
     } finally {
            //receivingMessages.set(false);  // ** This is new **
     }
.
.
```

`stop()` - removed `receivingMessages`:

```
@Override public void stop() {
        log.trace("[{}] Entry {}.stop", Thread.currentThread().getId(), this.getClass().getName());

        stopNow.set(true);

        synchronized(this) {         // ** This is new **
            // Close the connection to MQ to clean up
            if (reader != null) {
                reader.close();
            }
        }

        log.trace("[{}]  Exit {}.stop", Thread.currentThread().getId(), this.getClass().getName());
}
```

**Comment by AndrewJSchofield** [comment] 2020-11-19 20:51
I think I would be looking to call `reader.close()` in the `poll()` method. This is tricky because the code is also trying to minimise the amount of message duplication when the connector is stopped. The code is only calling `reader.close()` in the `stop()` method when the task is receiving messages from MQ. Otherwise, it wants to leave the connection open for the in-flight batch to commit, and then close it. The last bit of this is missing.

**Comment by AndrewJSchofield** [comment] 2020-11-19 20:52
Of course, what is really needed is KIP-419. Then the code would include the "missing" `reader.close()` in the `stopped()` method as a final clean up.

**Comment by khetanshu** [comment] 2020-11-19 21:07
Yes, I agree. So, in addition to the above changes, we can add a closing statement after [line 148](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/e8ea567053fd75c6484dd6f7db301288d23ae7a0/src/main/java/com/ibm/eventstreams/connect/mqsource/MQSourceTask.java#L148) , as follows,

```
.
.
// Close the connection to MQ to clean up
  if (reader != null) {
      reader.close();
  }
.
.
```

Please confirm if this looks fine to you, I can raise a PR for this.

**Comment by AndrewJSchofield** [comment] 2020-11-19 21:21
You've definitely found a bug, but it's really hard to test this because the overlapping and interleaving of calls to `poll()` and `stop()` is undefined. I have even seen a repeated call to `stop()` before. So try your fix, see if you're happy and put in a PR by all means.

**Comment by khetanshu** [comment] 2020-11-19 22:10
So, here are my thoughts, 

**What is the impact of this issue?** 
If an internal exception occurs, the connection will remain open with IBM-MQ; hence, the Batch's messages would be `blocked` in IBM-MQ (as `uncommitted`), which won't allow other tasks to pick those messages. 

**What is the impact of closing the connection irrespective of receiving messages in `poll()`?** 
It would close the connection with IBM-MQ when a `stop` signal is received, which would fix the above issue; however, there could be duplication of messages in the following specific scenario. 

If there is an inflight batch and if a `stop` signal is received (due to reasons like an internal exception, the closing of a task, etc.), the `stop()` will close the connection, and the task would be closed. When the task restarts or other task polls, then some written (fully or partially) messages would be received again from IBM-MQ as the batch won't have been committed in the last run.  

I believe this is fine behavior because it's an interruption/incomplete scenario from Kafka Connect. 

**What's next**
Now the question remains, as we don't have KIP-419 or another similar functionality, is there a better approach to fix this issue than following?

- Remove `receivingMessages`
- In `stop()`, close connection 
- In poll(), close connection after line 148

**Comment by khetanshu** [comment] 2020-11-19 23:34
To clarify, when I said an `Inflight Batch`, I meant the set of messages that have already been passed to Kafka connect, i.e., post `poll()` completion or, to be precise, when the control goes after [line 119](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/e8ea567053fd75c6484dd6f7db301288d23ae7a0/src/main/java/com/ibm/eventstreams/connect/mqsource/MQSourceTask.java#L119). Before this, if any `stop` signal is received, then the messages won't be returned by `poll()` due to the condition at [line 119](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/e8ea567053fd75c6484dd6f7db301288d23ae7a0/src/main/java/com/ibm/eventstreams/connect/mqsource/MQSourceTask.java#L119) as the `stopNow` would be `set` to `true` in `stop()` by now.

And this duplication of the `Inflight Batch` after `poll()` is present with the existing implementation. 

With the new changes, the current logic, i.e., closing the connection when `receivingMessage` will be present implicitly. Additionally, the connection will also get closed when we aren't receiving any messages.

**Comment by khetanshu** [comment] 2020-12-07 06:12
Created a PR for this issue [here](https://github.com/ibm-messaging/kafka-connect-mq-source/pull/76)

**Closed** 2023-01-05 14:56 UTC
